// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64
	ShortPath   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
