// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
)

const getLinkByPath = `-- name: GetLinkByPath :one
SELECT id, short_path, original_url, created_at, updated_at FROM links
WHERE short_path = $1
`

// GetLinkByPath
//
//	SELECT id, short_path, original_url, created_at, updated_at FROM links
//	WHERE short_path = $1
func (q *Queries) GetLinkByPath(ctx context.Context, shortPath string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByPath, shortPath)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortPath,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO links (short_path, original_url) VALUES ($1, $2)
`

type InsertLinkParams struct {
	ShortPath   string
	OriginalUrl string
}

// InsertLink
//
//	INSERT INTO links (short_path, original_url) VALUES ($1, $2)
func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.Exec(ctx, insertLink, arg.ShortPath, arg.OriginalUrl)
	return err
}
