version: '3'
dotenv: ['.env']
tasks:
  run:
    cmds:
    - go run cmd/main.go
  test:
    cmds:
    - golangci-lint run # brew install golangci-lint
    - go test ./...
    - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
  testv:
    cmds:
    - golangci-lint run
    - go test -race -shuffle=on -v ./... 
    - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
  build:
    vars:
      VERSION: 0.0.1
    cmds:
      - docker build
        -f configs/docker/dockerfile
        -t aaroncunliffe/link-shortener:{{.VERSION}}
        --build-arg VERSION={{.VERSION}}
        --build-arg BUILD_DATE={{ now | date "2006-01-02"}}
        .
  docker-compose-up:
    cmds:
    - docker compose -f configs/docker/compose.yml up
  docker-compose-down:
    cmds:
    - docker compose -f configs/docker/compose.yml down --rmi local --volumes
  demo:
    cmds:
    - docker compose -f configs/docker/compose.yml --profile demo up k6
  statviz:
    cmds:
    - open http://localhost:4040/debug/statsviz/ # macos specific
  db-inspect:
    cmds:
    - atlas schema inspect 
      -u "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" 
      --format "{{ printf "{{ sql . }}" }}" > configs/database/schema.sql
  db-migrate:
    cmds:
    - atlas schema apply 
      -u "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" 
      --to file://configs/database/schema.sql 
      --dev-url "docker://postgres/15"
  sqlc:
    cmds:
    - sqlc generate -f configs/database/sqlc.yaml 
