apiVersion: 1

datasources:
- name: Prometheus
  uid: prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  jsonData:
    timeInterval: 15s
  editable: true
- name: Postgres
  uid: postgres
  type: postgres
  url: db:5432
  user: postgres
  secureJsonData:
    password: 'password'
  jsonData:
      database: postgres
  postgresVersion: 1500 # 15
  sslmode: 'disable'