name: url-shortener
services:

  api:
    init: true
    build:
      context: ../../.
      dockerfile: configs/docker/dockerfile.dev
    ports:
      - 8080:8080 # web
      - 4040:4040 # debug
    volumes:
      - ../../.:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/debug/readiness"]
    stop_grace_period: 30s
    depends_on:
      - db
  db:
    image: postgres:15-alpine  
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persist data using a named volume
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro # Auto apply our schema
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - api
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yaml:ro
    depends_on:
      - api
  alloy:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data

      # bind docker socket - only acceptable locally
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    depends_on:
      - loki
  tempo:
    image: grafana/tempo:latest
    command: [ "-target=all", "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
  k6:
    image: grafana/k6:latest
    profiles: ["demo"]
    depends_on:
      api:
        condition: service_healthy
    environment:
      - TARGET_URL=api:8080
    volumes:
      - ./k6:/scripts:ro
    command: run /scripts/demo.js

# Volumes - for data persistence between restarts
volumes:
  pg_data:
  prometheus_data:
  alloy_data:
  loki_data:
  tempo_data:
