services:
  api:
    build:
      context: ../../.
      dockerfile: configs/docker/dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - ../../.:/app
    depends_on:
      - db
  db:
    image: postgres:15-alpine  
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data using a named volume

volumes:
  pgdata: