ARG GO_VERSION=1.26.0
FROM golang:${GO_VERSION}-alpine

WORKDIR /app

RUN apk add --no-cache curl
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
